variables:
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  BRANCH_NAME: ci-fix
  DOCKER_TLS_CERTDIR: "/certs"
  CI_HOME_FOLDER: /opt/gitlab-words-ci
  HUGO_PATH: $CI_HOME_FOLDER/bins/hugo

stages:
  - test

.rules:branch:
  rules:
    - if: "$CI_COMMIT_BRANCH == $BRANCH_NAME"
      when: on_success
    - when: never

.scripts:
  apk_cache_setup: &apk_cache_setup
    - mkdir -p .apk-cache
    - export APK_CACHE_DIR="$(pwd)/.apk-cache"
    - mkdir -p /etc/apk
    - echo "cache-dir = $APK_CACHE_DIR" > /etc/apk/apk.conf

test:
  stage: test
  image: node:25.9-alpine
  extends: .rules:branch
  variables:
    GIT_STRATEGY: none
  cache:
    key: "$CI_COMMIT_REF_SLUG-apk-npm"
    paths:
      - .apk-cache/
      - .npm-cache/
    policy: pull-push
  before_script:
    - *apk_cache_setup
    - npm config set cache "$CI_PROJECT_DIR/.npm-cache"
  script:
    - chmod +x $HUGO_PATH
    - $HUGO_PATH version
